# Generated by Django 4.2.7 on 2024-01-13 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_profile_academic_group_profile_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='academic_group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='study_direction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='third_name',
        ),
        migrations.CreateModel(
            name='ProfileNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('third_name', models.CharField(blank=True, max_length=100, null=True)),
                ('study_direction', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.IntegerField(blank=True, null=True)),
                ('academic_group', models.CharField(blank=True, max_length=10, null=True)),
                ('contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
